### ISSUE TITLE
Info about cargo-flash/cargo-embed

### ISSUE THREAD

**Issue by apatrushev** [rubberduck203/stm32f3-discovery#45]
How do you think would it be helpful for newcomers to note in this repo or may be in discovery book about easiest way to try examples with discovery board:
```
cargo install cargo-flash
cargo flash --chip stm32f3 --example leds --connect-under-reset
```
I think it can help newcomers to to start as quick as they type only 3 commands.

**Comment by rubberduck203** [comment]
This crate is just a replacement for the defunct `f3` crate.
My documentation just points to the Rust Embedded and Discovery books.

What I'm trying to say is that it's not my goal to teach newbies how to run their code, because there are other resources for that.
So, I kind of feel like that is out of scope here.

There is also the `probe-run` tool, which I also don't use, so which do I write documentation for?
All 3?
That's not really something I want to get myself into when the community hasn't gelled on a preferred toolchain.

I'm not saying it isn't a good idea, just that it should be the realm of one of the books or a blog post.

**Comment by apatrushev** [comment]
STM32F3DISCOVERY is more about education by its nature. I just thought that it would be helpful to have short note about "Quick Start". Anyway you are an author and it is up to you.

**Comment by rubberduck203** [comment]
I think it’s a wonderful idea. 
I just think it belongs in the book. 

I’m glad to know you’ve found the crate useful. 
I sincerely hope I’ve not upset you.
